version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      red:
    environment:
     PHP_USER_ID: 1000
     TZ: America/Buenos_Aires
  postgres:
     image: postgres:9.6.12
     container_name: postgresefipuno
     volumes:
     - ./bd:/docker-entrypoint-initdb.d
     - pgdata:/var/lib/postgresql/data
     environment:
        POSTGRES_DB: seminariofinal
        POSTGRES_PASSWORD: seminariofinal
     networks:
      red:
volumes:
  pgdata:
networks:
  red:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.69.0/24
     