version: '2.4'
services:
  php:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      red:
    environment:
     PHP_USER_ID: 1000
     TZ: America/Buenos_Aires
  postgres:
     image: postgres:9.6.12
     container_name: postgrestfg
     volumes:
     - ./bd:/docker-entrypoint-initdb.d
     - pgdata:/var/lib/postgresql/data
     environment:
        POSTGRES_DB: seminariofinal
        POSTGRES_PASSWORD: seminariofinal
     networks:
      red:
  flask:
      image: python-docker:latest
      build:
        context: ./flaskserver
      volumes:
       - ./flaskserver:/app:delegated
      environment:
          FLASK_DEBUG: 1
          FLASK_ENV: development          
      networks:
        red:
volumes:
  pgdata:
networks:
  red:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.69.0/24
     