#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

 defined('YII_ENV') or define('YII_ENV', getenv('RUN_MODE') ? getenv('RUN_MODE') : 'dev');
 defined('YII_DEBUG') or define('YII_DEBUG', (YII_ENV==='dev' || YII_ENV==='test'));

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/common.php'),
    require(__DIR__ . '/config/console.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
