<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Expression;


/**
 * This is the base-model class for table "actividad".
 *
 * @property integer $id
 * @property string $descripcion
 * @property integer $subcategoriaid
 * @property integer $dificultad
 * @property integer $multimediaid
 * @property integer $activo
 * @property string $fecha_actualizacion
 * @property integer $creado_porid
 * @property integer $actualizado_porid
 * @property integer $version
 * @property string $fecha_creacion
 *
 * @property \app\models\Multimedia $multimedia
 * @property \app\models\Subcategoria $subcategoria
 * @property \app\models\User $creadoPor
 * @property \app\models\User $actualizadoPor
 * @property \app\models\ActividadOpcion[] $actividadOpcions
 * @property \app\models\CuestionarioActividad[] $cuestionarioActividads
 * @property \app\models\Cuestionario[] $actividads
 * @property string $aliasModel
 */
abstract class Actividad extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'actividad';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'creado_porid',
                'updatedByAttribute' => 'actualizado_porid',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'fecha_creacion',
                'updatedAtAttribute' => 'fecha_actualizacion',
                'value'=>new Expression('NOW()')
                
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['descripcion', 'subcategoriaid', 'dificultad', 'multimediaid'], 'required'],
            [['subcategoriaid', 'dificultad', 'multimediaid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'default', 'value' => null],
            [['subcategoriaid', 'dificultad', 'multimediaid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'integer'],
            [['fecha_actualizacion'], 'safe'],
            [['descripcion'], 'string', 'max' => 255],
            [['multimediaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Multimedia::className(), 'targetAttribute' => ['multimediaid' => 'id']],
            [['subcategoriaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Subcategoria::className(), 'targetAttribute' => ['subcategoriaid' => 'id']],
            [['creado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['creado_porid' => 'id']],
            [['actualizado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['actualizado_porid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'descripcion' => 'Descripcion',
            'subcategoriaid' => 'Subcategoriaid',
            'dificultad' => 'Dificultad',
            'multimediaid' => 'Multimediaid',
            'activo' => 'Activo',
            'fecha_creacion' => 'Fecha Creacion',
            'fecha_actualizacion' => 'Fecha Actualizacion',
            'creado_porid' => 'Creado Porid',
            'actualizado_porid' => 'Actualizado Porid',
            'version' => 'Version',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMultimedia()
    {
        return $this->hasOne(\app\models\Multimedia::className(), ['id' => 'multimediaid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubcategoria()
    {
        return $this->hasOne(\app\models\Subcategoria::className(), ['id' => 'subcategoriaid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'creado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActualizadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'actualizado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActividadOpcions()
    {
        return $this->hasMany(\app\models\ActividadOpcion::className(), ['actividadid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuestionarioActividads()
    {
        return $this->hasMany(\app\models\CuestionarioActividad::className(), ['cuestionarioid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActividads()
    {
        return $this->hasMany(\app\models\Cuestionario::className(), ['id' => 'actividadid'])->viaTable('cuestionario_actividad', ['cuestionarioid' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\ActividadQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ActividadQuery(get_called_class());
    }


}
