<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the base-model class for table "cuestionario".
 *
 * @property integer $id
 * @property string $descripcion
 * @property integer $activo
 * @property string $fecha_actualizacion
 * @property integer $creado_porid
 * @property integer $actualizado_porid
 * @property integer $version
 * @property string $fecha_creacion
 *
 * @property \app\models\User $creadoPor
 * @property \app\models\User $actualizadoPor
 * @property \app\models\CuestionarioActividad[] $cuestionarioActividads
 * @property \app\models\Actividad[] $actividades
 * @property \app\models\IntentoResolucion[] $intentoResolucions
 * @property string $aliasModel
 */
abstract class Cuestionario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cuestionario';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'creado_porid',
                'updatedByAttribute' => 'actualizado_porid',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'fecha_creacion',
                'updatedAtAttribute' => 'fecha_actualizacion',
                'value'=>new Expression('NOW()')
                
            ],
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['descripcion'], 'required'],
            [['activo', 'creado_porid', 'actualizado_porid', 'version'], 'default', 'value' => null],
            [['activo', 'creado_porid', 'actualizado_porid', 'version'], 'integer'],
            [['fecha_actualizacion'], 'safe'],
            [['descripcion'], 'string', 'max' => 255],
            [['creado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['creado_porid' => 'id']],
            [['actualizado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['actualizado_porid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'descripcion' => 'Descripcion',
            'activo' => 'Activo',
            'fecha_creacion' => 'Fecha Creacion',
            'fecha_actualizacion' => 'Fecha Actualizacion',
            'creado_porid' => 'Creado Porid',
            'actualizado_porid' => 'Actualizado Porid',
            'version' => 'Version',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'creado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActualizadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'actualizado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuestionarioActividads()
    {
        return $this->hasMany(\app\models\CuestionarioActividad::className(), ['actividadid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActividades()
    {
        return $this->hasMany(\app\models\Actividad::className(), ['id' => 'actividadid'])->viaTable('cuestionario_actividad', ['cuestionarioid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIntentoResolucions()
    {
        return $this->hasMany(\app\models\IntentoResolucion::className(), ['cuestionarioid' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\CuestionarioQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\CuestionarioQuery(get_called_class());
    }


}
