<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the base-model class for table "cuestionario_actividad".
 *
 * @property integer $cuestionarioid
 * @property integer $actividadid
 * @property integer $activo
 * @property string $fecha_actualizacion
 * @property integer $creado_porid
 * @property integer $actualizado_porid
 * @property integer $version
 * @property string $fecha_creacion
 *
 * @property \app\models\Actividad $cuestionario
 * @property \app\models\Cuestionario $actividad
 * @property \app\models\User $creadoPor
 * @property \app\models\User $actualizadoPor
 * @property string $aliasModel
 */
abstract class CuestionarioActividad extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cuestionario_actividad';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'creado_porid',
                'updatedByAttribute' => 'actualizado_porid',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'fecha_creacion',
                'updatedAtAttribute' => 'fecha_actualizacion',
                'value'=>new Expression('NOW()')
                
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cuestionarioid', 'actividadid'], 'required'],
            [['cuestionarioid', 'actividadid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'default', 'value' => null],
            [['cuestionarioid', 'actividadid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'integer'],
            [['fecha_actualizacion'], 'safe'],
            [['cuestionarioid', 'actividadid'], 'unique', 'targetAttribute' => ['cuestionarioid', 'actividadid']],
            [['cuestionarioid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Actividad::className(), 'targetAttribute' => ['cuestionarioid' => 'id']],
            [['actividadid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Cuestionario::className(), 'targetAttribute' => ['actividadid' => 'id']],
            [['creado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['creado_porid' => 'id']],
            [['actualizado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['actualizado_porid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'cuestionarioid' => 'Cuestionarioid',
            'actividadid' => 'Actividadid',
            'activo' => 'Activo',
            'fecha_creacion' => 'Fecha Creacion',
            'fecha_actualizacion' => 'Fecha Actualizacion',
            'creado_porid' => 'Creado Porid',
            'actualizado_porid' => 'Actualizado Porid',
            'version' => 'Version',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuestionario()
    {
        return $this->hasOne(\app\models\Actividad::className(), ['id' => 'cuestionarioid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActividad()
    {
        return $this->hasOne(\app\models\Cuestionario::className(), ['id' => 'actividadid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'creado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActualizadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'actualizado_porid']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\CuestionarioActividadQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\CuestionarioActividadQuery(get_called_class());
    }


}
