<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the base-model class for table "intento_resolucion".
 *
 * @property integer $id
 * @property integer $userid
 * @property integer $cuestionarioid
 * @property integer $tipo_finalizacion_cuestionarioid
 * @property string $retroalimentacion
 * @property integer $activo
 * @property string $fecha_actualizacion
 * @property integer $creado_porid
 * @property integer $actualizado_porid
 * @property integer $version
 * @property string $fecha_creacion
 *
 * @property \app\models\Cuestionario $cuestionario
 * @property \app\models\TipoFinalizacionCuestionario $tipoFinalizacionCuestionario
 * @property \app\models\User $user
 * @property \app\models\User $creadoPor
 * @property \app\models\User $actualizadoPor
 * @property \app\models\OpcionIntentoResolucion[] $opcionIntentoResolucions
 * @property string $aliasModel
 */
abstract class IntentoResolucion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'intento_resolucion';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'creado_porid',
                'updatedByAttribute' => 'actualizado_porid',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'fecha_creacion',
                'updatedAtAttribute' => 'fecha_actualizacion',
                'value'=>new Expression('NOW()')
                
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userid', 'cuestionarioid', 'tipo_finalizacion_cuestionarioid'], 'required'],
            [['userid', 'cuestionarioid', 'tipo_finalizacion_cuestionarioid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'default', 'value' => null],
            [['userid', 'cuestionarioid', 'tipo_finalizacion_cuestionarioid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'integer'],
            [['fecha_actualizacion'], 'safe'],
            [['retroalimentacion'], 'string', 'max' => 255],
            [['cuestionarioid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Cuestionario::className(), 'targetAttribute' => ['cuestionarioid' => 'id']],
            [['tipo_finalizacion_cuestionarioid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoFinalizacionCuestionario::className(), 'targetAttribute' => ['tipo_finalizacion_cuestionarioid' => 'id']],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['userid' => 'id']],
            [['creado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['creado_porid' => 'id']],
            [['actualizado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['actualizado_porid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => 'Userid',
            'cuestionarioid' => 'Cuestionarioid',
            'tipo_finalizacion_cuestionarioid' => 'Tipo Finalizacion Cuestionarioid',
            'retroalimentacion' => 'Retroalimentacion',
            'activo' => 'Activo',
            'fecha_creacion' => 'Fecha Creacion',
            'fecha_actualizacion' => 'Fecha Actualizacion',
            'creado_porid' => 'Creado Porid',
            'actualizado_porid' => 'Actualizado Porid',
            'version' => 'Version',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuestionario()
    {
        return $this->hasOne(\app\models\Cuestionario::className(), ['id' => 'cuestionarioid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoFinalizacionCuestionario()
    {
        return $this->hasOne(\app\models\TipoFinalizacionCuestionario::className(), ['id' => 'tipo_finalizacion_cuestionarioid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'userid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'creado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActualizadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'actualizado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOpcionIntentoResolucions()
    {
        return $this->hasMany(\app\models\OpcionIntentoResolucion::className(), ['intento_resolucionid' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\IntentoResolucionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\IntentoResolucionQuery(get_called_class());
    }


}
