<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "opcion_intento_resolucion".
 *
 * @property integer $id
 * @property integer $intento_resolucionid
 * @property integer $actividad_opcionid
 * @property integer $activo
 * @property string $fecha_actualizacion
 * @property integer $creado_porid
 * @property integer $actualizado_porid
 * @property integer $version
 * @property string $fecha_creacion
 *
 * @property \app\models\ActividadOpcion $actividadOpcion
 * @property \app\models\IntentoResolucion $intentoResolucion
 * @property \app\models\User $creadoPor
 * @property \app\models\User $actualizadoPor
 * @property string $aliasModel
 */
abstract class OpcionIntentoResolucion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'opcion_intento_resolucion';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'creado_porid',
                'updatedByAttribute' => 'actualizado_porid',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'fecha_creacion',
                'updatedAtAttribute' => 'fecha_actualizacion',
                'value'=>new Expression('NOW()')
                
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['intento_resolucionid', 'actividad_opcionid'], 'required'],
            [['intento_resolucionid', 'actividad_opcionid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'default', 'value' => null],
            [['intento_resolucionid', 'actividad_opcionid', 'activo', 'creado_porid', 'actualizado_porid', 'version'], 'integer'],
            [['fecha_actualizacion'], 'safe'],
            [['actividad_opcionid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ActividadOpcion::className(), 'targetAttribute' => ['actividad_opcionid' => 'id']],
            [['intento_resolucionid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\IntentoResolucion::className(), 'targetAttribute' => ['intento_resolucionid' => 'id']],
            [['creado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['creado_porid' => 'id']],
            [['actualizado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['actualizado_porid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'intento_resolucionid' => 'Intento Resolucionid',
            'actividad_opcionid' => 'Actividad Opcionid',
            'activo' => 'Activo',
            'fecha_creacion' => 'Fecha Creacion',
            'fecha_actualizacion' => 'Fecha Actualizacion',
            'creado_porid' => 'Creado Porid',
            'actualizado_porid' => 'Actualizado Porid',
            'version' => 'Version',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActividadOpcion()
    {
        return $this->hasOne(\app\models\ActividadOpcion::className(), ['id' => 'actividad_opcionid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIntentoResolucion()
    {
        return $this->hasOne(\app\models\IntentoResolucion::className(), ['id' => 'intento_resolucionid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'creado_porid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActualizadoPor()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'actualizado_porid']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\OpcionIntentoResolucionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\OpcionIntentoResolucionQuery(get_called_class());
    }


}
