<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use app\models\PacienteObraSocial;
use app\models\Persona;
use app\models\query\PacienteQuery;
use app\models\Turno;
use app\models\User;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the base-model class for table "paciente".
 *
 * @property integer $personaid
 * @property integer $activo
 * @property integer $version
 * @property string $fecha_creacion
 * @property string $fecha_actualizacion
 * @property integer $creado_porid
 * @property integer $actualizado_porid
 *
 * @property Persona $persona
 * @property User $creadoPor
 * @property User $actualizadoPor
 * @property PacienteObraSocial[] $pacienteObraSocials
 * @property Turno[] $turnos
 * @property string $aliasModel
 */
abstract class Paciente extends ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'paciente';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'creado_porid',
                'updatedByAttribute' => 'actualizado_porid',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'fecha_creacion',
                'updatedAtAttribute' => 'fecha_actualizacion',
                'value'=>new Expression('NOW()')
                
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['personaid'], 'required'],
            [['personaid', 'activo', 'version'], 'default', 'value' => null],
            [['personaid', 'activo', 'version'], 'integer'],
            [['personaid'], 'unique'],
            [['personaid'], 'exist', 'skipOnError' => true, 'targetClass' => Persona::className(), 'targetAttribute' => ['personaid' => 'id']],
            [['creado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['creado_porid' => 'id']],
            [['actualizado_porid'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['actualizado_porid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'personaid' => 'Personaid',
            'activo' => 'Activo',
            'fecha_creacion' => 'Fecha Creacion',
            'fecha_actualizacion' => 'Fecha Actualizacion',
            'creado_porid' => 'Creado Porid',
            'actualizado_porid' => 'Actualizado Porid',
            'version' => 'Version',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getPersona()
    {
        return $this->hasOne(Persona::className(), ['id' => 'personaid']);
    }

    /**
     * @return ActiveQuery
     */
    public function getCreadoPor()
    {
        return $this->hasOne(User::className(), ['id' => 'creado_porid']);
    }

    /**
     * @return ActiveQuery
     */
    public function getActualizadoPor()
    {
        return $this->hasOne(User::className(), ['id' => 'actualizado_porid']);
    }

    /**
     * @return ActiveQuery
     */
    public function getPacienteObraSocials()
    {
        return $this->hasMany(PacienteObraSocial::className(), ['pacienteid' => 'personaid']);
    }

    /**
     * @return ActiveQuery
     */
    public function getTurnos()
    {
        return $this->hasMany(Turno::className(), ['pacienteid' => 'personaid']);
    }


    
    /**
     * @inheritdoc
     * @return PacienteQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PacienteQuery(get_called_class());
    }


}
