<?php

return [
    [
        'id' => 1,
        'pregunta' => 28,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => 1,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 2,
        'pregunta' => 35,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 3,
        'pregunta' => 66,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 4,
        'pregunta' => 86,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 5,
        'pregunta' => 54,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 6,
        'pregunta' => 30,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 7,
        'pregunta' => 52,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 8,
        'pregunta' => 29,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 9,
        'pregunta' => 46,
        'mensaje' => 'Opción correcta',
        'opcion_correcta' => 1,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 10,
        'pregunta' => 84,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 11,
        'pregunta' => 82,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 12,
        'pregunta' => 86,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 13,
        'pregunta' => 75,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 14,
        'pregunta' => 40,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 15,
        'pregunta' => 20,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 16,
        'pregunta' => 42,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 17,
        'pregunta' => 98,
        'mensaje' => 'Opción correcta',
        'opcion_correcta' => 1,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 18,
        'pregunta' => 93,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 19,
        'pregunta' => 72,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 20,
        'pregunta' => 68,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 21,
        'pregunta' => 47,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 22,
        'pregunta' => 17,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 23,
        'pregunta' => 24,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 24,
        'pregunta' => 43,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 25,
        'pregunta' => 93,
        'mensaje' => 'Opción correcta',
        'opcion_correcta' => 1,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 26,
        'pregunta' => 78,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 27,
        'pregunta' => 20,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 28,
        'pregunta' => 41,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 29,
        'pregunta' => 98,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 30,
        'pregunta' => 10,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 31,
        'pregunta' => 39,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 32,
        'pregunta' => 50,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 33,
        'pregunta' => 96,
        'mensaje' => 'Opción correcta',
        'opcion_correcta' => 1,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 34,
        'pregunta' => 24,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 35,
        'pregunta' => 87,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 36,
        'pregunta' => 74,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 37,
        'pregunta' => 54,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 38,
        'pregunta' => 74,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 39,
        'pregunta' => 71,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 40,
        'pregunta' => 96,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 41,
        'pregunta' => 81,
        'mensaje' => 'Opción correcta',
        'opcion_correcta' => 1,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 42,
        'pregunta' => 89,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 43,
        'pregunta' => 80,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 44,
        'pregunta' => 54,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 45,
        'pregunta' => 17,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 46,
        'pregunta' => 63,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 47,
        'pregunta' => 14,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 48,
        'pregunta' => 91,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 49,
        'pregunta' => 67,
        'mensaje' => 'Opción correcta',
        'opcion_correcta' => 1,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 50,
        'pregunta' => 90,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 51,
        'pregunta' => 88,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 52,
        'pregunta' => 55,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 53,
        'pregunta' => 79,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 54,
        'pregunta' => 72,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 55,
        'pregunta' => 40,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 56,
        'pregunta' => 50,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 57,
        'pregunta' => 49,
        'mensaje' => 'Opción correcta',
        'opcion_correcta' => 1,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 58,
        'pregunta' => 69,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 59,
        'pregunta' => 98,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 60,
        'pregunta' => 67,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 61,
        'pregunta' => 25,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 62,
        'pregunta' => 69,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 63,
        'pregunta' => 78,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 64,
        'pregunta' => 37,
        'mensaje' => 'Opción incorrecta',
        'opcion_correcta' => false,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
];