<?php

return [
    [
        'id' => 1,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 2,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 3,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 4,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 5,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 6,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 7,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 8,
        'descripcion' => '¿Cuál es el resultado de la suma?',
        'subcategoriaid' => 1,
        'dificultad' => 2,
        'multimediaid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
];