<?php

return [
    [
        'cuestionarioid' => 1,
        'actividadid' => 1,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'cuestionarioid' => 1,
        'actividadid' => 2,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'cuestionarioid' => 1,
        'actividadid' => 3,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'cuestionarioid' => 1,
        'actividadid' => 4,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'cuestionarioid' => 1,
        'actividadid' => 5,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'cuestionarioid' => 1,
        'actividadid' => 6,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'cuestionarioid' => 1,
        'actividadid' => 7,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'cuestionarioid' => 1,
        'actividadid' => 8,
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
];