<?php

return [
    [
        'id' => 1,
        'nombre_archivo' => 'imagen_suma_15mas13',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 2,
        'nombre_archivo' => 'imagen_suma_21mas25',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 3,
        'nombre_archivo' => 'imagen_suma_66mas32',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 4,
        'nombre_archivo' => 'imagen_suma_60mas33',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 5,
        'nombre_archivo' => 'imagen_suma_82mas14',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 6,
        'nombre_archivo' => 'imagen_suma_70mas11',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 7,
        'nombre_archivo' => 'imagen_suma_52mas15',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
    [
        'id' => 8,
        'nombre_archivo' => 'imagen_suma_34mas15',
        'tipo' => 'jpg',
        'activo' => 1,
        'fecha_creacion' => '2021-01-01 00:00:00',
        'fecha_actualizacion' => null,
        'creado_porid' => 1,
        'actualizado_porid' => null,
        'version' => 0,
    ],
];